In [1]:
# attribute 1
import numpy as np
print(np.__version__)

1.16.5


In [4]:
# method 2
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# method 3
a = np.full((3,3), True, dtype = bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# method 4
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
# method 5
arr = np.arange(10)
out = arr.reshape((2, 5))
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
# method 6
a = np.arange(10).reshape(2,-1)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
# method 7
b = np.repeat(1, 10).reshape(2,-1)
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
# method 8
print(np.concatenate([a, b], axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
# method 9
print(np.vstack([a, b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
# method 10
print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
# method 11
print(np.concatenate([a, b], axis=1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [19]:
# method 12
print(np.hstack([a, b]))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [20]:
# method 13
print(np.c_[a, b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [22]:
# method 14
a = np.array([1,2,3])
print(np.r_[np.repeat(a,3), np.tile(a,3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [23]:
# method 15
a = np.array([1,5,6,3,2])
b = np.array([9,8,5,7,3,2])
np.intersect1d(a,b)

array([2, 3, 5])

In [24]:
# method 16
a = np.array([1,5,6,3,2])
b = np.array([9,8,5,7,3,2])
np.setdiff1d(a,b)

array([1, 6])

In [26]:
# method 17
a = np.array([1,5,6,3,2])
b = np.array([9,8,5,7,2])
np.where(a==b)

(array([4], dtype=int64),)

In [27]:
# method 18
a = np.arange(15)
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
# method 19
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

array([6., 7., 9., 8., 9., 7., 5.])

In [30]:
# method 20
arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(arr[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [31]:
# method 21
arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(arr[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [34]:
# method 22
arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [35]:
# method 23
arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(arr[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [36]:
# method 24
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[7.47970901 9.61940527 7.04484583]
 [6.34583069 7.96530786 5.31098995]
 [8.69724044 6.70154067 7.19979755]
 [5.54414514 8.94660281 8.63689201]
 [5.75786404 7.79155188 5.95591236]]


In [37]:
# method 25
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[6.12820276 9.49483136 8.21221502]
 [6.71521032 7.59040372 9.06599575]
 [9.25504813 7.87917713 6.78729549]
 [8.76458827 8.29362955 7.67254357]
 [9.47102569 9.26684546 6.03202713]]


In [41]:
# method 26
rand_arr = np.random.random([5,3])
np.set_printoptions(precision=3)
print(rand_arr)

[[0.97  0.003 0.561]
 [0.741 0.505 0.235]
 [0.749 0.819 0.533]
 [0.24  0.471 0.875]
 [0.6   0.75  0.933]]


In [42]:
# method 27
np.set_printoptions(suppress=False)
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [43]:
# method 28
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [47]:
# method 29
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [49]:
# method 30
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
print(species[:5])

(150,)
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


C:\Users\Muhammad Abu Bakar\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


In [50]:
# method 31
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


C:\Users\Muhammad Abu Bakar\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


In [51]:
# method 32
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Alt Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


C:\Users\Muhammad Abu Bakar\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


In [61]:
# method 33
l = np.arange(100).reshape(10, 10)
print(l)
for i in range(10):
    print(np.mean(l[i]))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
4.5
14.5
24.5
34.5
44.5
54.5
64.5
74.5
84.5
94.5


In [62]:
# method 34
l = np.arange(100).reshape(10, 10)
print(l)
for i in range(10):
    print(np.median(l[i]))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
4.5
14.5
24.5
34.5
44.5
54.5
64.5
74.5
84.5
94.5


In [65]:
# method 35
l = np.arange(100).reshape(10, 10)
print(l)
for i in range(10):
    print(np.std(l[i]))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
2.8722813232690143
2.8722813232690143
2.8722813232690143
2.8722813232690143
2.8722813232690143
2.8722813232690143
2.8722813232690143
2.8722813232690143
2.8722813232690143
2.8722813232690143


In [67]:
# method 36
l = np.arange(100).reshape(10, 10)
print(l)
for i in range(10):
    print(np.min(l[i]))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
0
10
20
30
40
50
60
70
80
90


In [68]:
# method 37
l = np.arange(100).reshape(10, 10)
print(l)
for i in range(10):
    print(np.max(l[i]))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
9
19
29
39
49
59
69
79
89
99


In [69]:
# method 38
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(l))

[[8.194e-40 8.194e-40 8.194e-40 8.194e-40 8.194e-40 8.194e-40 8.194e-40
  8.194e-40 8.194e-40 8.194e-40]
 [1.805e-35 1.805e-35 1.805e-35 1.805e-35 1.805e-35 1.805e-35 1.805e-35
  1.805e-35 1.805e-35 1.805e-35]
 [3.975e-31 3.975e-31 3.975e-31 3.975e-31 3.975e-31 3.975e-31 3.975e-31
  3.975e-31 3.975e-31 3.975e-31]
 [8.756e-27 8.756e-27 8.756e-27 8.756e-27 8.756e-27 8.756e-27 8.756e-27
  8.756e-27 8.756e-27 8.756e-27]
 [1.929e-22 1.929e-22 1.929e-22 1.929e-22 1.929e-22 1.929e-22 1.929e-22
  1.929e-22 1.929e-22 1.929e-22]
 [4.248e-18 4.248e-18 4.248e-18 4.248e-18 4.248e-18 4.248e-18 4.248e-18
  4.248e-18 4.248e-18 4.248e-18]
 [9.357e-14 9.357e-14 9.357e-14 9.357e-14 9.357e-14 9.357e-14 9.357e-14
  9.357e-14 9.357e-14 9.357e-14]
 [2.061e-09 2.061e-09 2.061e-09 2.061e-09 2.061e-09 2.061e-09 2.061e-09
  2.061e-09 2.061e-09 2.061e-09]
 [4.540e-05 4.540e-05 4.540e-05 4.540e-05 4.540e-05 4.540e-05 4.540e-05
  4.540e-05 4.540e-05 4.540e-05]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.0

In [70]:
# method 39
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
print(iris_2d[any_nan_in_row][:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.4 3.9 1.7 0.4]]


In [71]:
# method 40
print(np.isnan(l).any())

False


In [72]:
# method 41
iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [73]:
# method 42
print(np.unique(l, return_counts=True))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


In [76]:
# method 43

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])


label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
print(petal_length_cat)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

In [80]:
# method 44
np.random.seed(100)
a = [0,1,2]
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
print(species_out)

[1 0 0 ... 1 0 0]


In [82]:
# method 45
print(l)
print(np.unique(np.sort(l))[-2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
98


In [83]:
# method 46
print(l[l[:,0].argsort()][:20])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [87]:
# method 47
print(np.argwhere(l[:,4].astype(float) > 1)[0])

[0]


In [88]:
# method 48
print(np.clip(l, a_min=10, a_max=30))

[[10 10 10 10 10 10 10 10 10 10]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]


In [92]:
# method 49
np.random.seed(100)
a = np.random.uniform(1,50, 5)
print(a)
print(a.argsort())

[27.627 14.64  21.801 42.394  1.231]
[4 1 2 0 3]


In [91]:
# method 50
np.random.seed(100)
a = np.random.uniform(1,50, 5)
print(a)
print(np.sort(a)[-5:])

[ 1.231 14.64  21.801 27.627 42.394]
